#!/bin/bash

# ============================================================
# RIST Multi-Receiver - Auto Install Script (Linux / Mac)
# ============================================================
# Detects port conflicts and auto-assigns alternatives
# Usage: bash install.sh
# ============================================================

set -e

CYAN='\033[1;36m'; GREEN='\033[1;32m'; YELLOW='\033[1;33m'
RED='\033[1;31m'; BOLD='\033[1m'; NC='\033[0m'

banner() {
  echo -e "${CYAN}"
  echo "  ██████╗ ██╗███████╗████████╗"
  echo "  ██╔══██╗██║██╔════╝╚══██╔══╝"
  echo "  ██████╔╝██║███████╗   ██║   "
  echo "  ██╔══██╗██║╚════██║   ██║   "
  echo "  ██║  ██║██║███████║   ██║   "
  echo "  ╚═╝  ╚═╝╚═╝╚══════╝   ╚═╝   Multi-Receiver"
  echo -e "${NC}"
  echo -e "${BOLD}  Reliable Internet Stream Transport${NC}"
  echo ""
}

check_command() {
  command -v "$1" &>/dev/null || {
    echo -e "${RED}✕ '$1' not found. Please install it first.${NC}"
    exit 1
  }
}

# Check if a TCP port is free
is_tcp_port_free() {
  local port=$1
  if command -v ss &>/dev/null; then
    ! ss -tlnp 2>/dev/null | grep -q ":${port} "
  elif command -v netstat &>/dev/null; then
    ! netstat -tlnp 2>/dev/null | grep -q ":${port} "
  else
    ! (echo "" > /dev/tcp/127.0.0.1/${port}) 2>/dev/null
  fi
}

# Find next free TCP port starting from $1
find_free_tcp_port() {
  local port=$1
  while ! is_tcp_port_free $port; do
    echo -e "  ${YELLOW}⚠ TCP Port ${port} is already in use. Trying $((port + 1))...${NC}" >&2
    port=$((port + 1))
  done
  echo $port
}

# Get public IP
get_public_ip() {
  curl -s --max-time 4 "https://api.ipify.org" 2>/dev/null || echo "YOUR_SERVER_IP"
}

# Get local LAN IP
get_local_ip() {
  hostname -I 2>/dev/null | awk '{print $1}' || ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || echo "localhost"
}

# ============================================================

banner

echo -e "${BOLD}Checking requirements...${NC}"
check_command docker
check_command git
echo -e "${GREEN}✓ Docker found: $(docker --version)${NC}"
echo ""

# ===== PORT DETECTION =====
echo -e "${BOLD}Scanning for available ports...${NC}"

WEB_PORT=$(find_free_tcp_port 3000)

if [ "$WEB_PORT" -ne 3000 ]; then
  echo -e "  ${GREEN}✓ Web UI: Using alternative port ${BOLD}${WEB_PORT}${NC}${GREEN} (3000 was busy)${NC}"
else
  echo -e "  ${GREEN}✓ Web UI: Port ${BOLD}${WEB_PORT}${NC}${GREEN} is free${NC}"
fi

PUBLIC_IP=$(get_public_ip)
LOCAL_IP=$(get_local_ip)

echo ""
echo -e "  ${CYAN}🌐 Public IP detected: ${BOLD}${PUBLIC_IP}${NC}"
echo -e "  ${CYAN}🏠 LAN IP detected:    ${BOLD}${LOCAL_IP}${NC}"
echo ""

# ===== WRITE .env FILE =====
echo -e "${BOLD}Writing configuration to .env...${NC}"

cat > .env <<EOF
# Generated by install.sh on $(date)

# Web Dashboard Port (auto-detected, free port)
PORT=${WEB_PORT}

# Physical host LAN IP - used to show correct IP in dashboard dropdowns
HOST_IP=${LOCAL_IP}
EOF

echo -e "${GREEN}✓ .env file created${NC}"
echo ""

# ===== UPDATE docker-compose.yml PORT MAPPING =====
if [ "$WEB_PORT" -ne 3000 ]; then
  echo -e "${BOLD}Updating docker-compose.yml to expose port ${WEB_PORT}...${NC}"
  sed -i "s|\"3000:3000/tcp\"|\"${WEB_PORT}:3000/tcp\"|g" docker-compose.yml
  echo -e "${GREEN}✓ docker-compose.yml updated${NC}"
  echo ""
fi

# ===== DOCKER COMPOSE UP =====
echo -e "${BOLD}Building and starting containers...${NC}"
docker compose up -d --build
echo ""

# ===== DONE =====
API_KEY=$(cat data/.apikey 2>/dev/null || echo "(not yet generated - check docker logs)")

echo ""
echo -e "${CYAN}════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✓ RIST Multi-Receiver is Running!${NC}"
echo -e "${CYAN}════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Web Dashboard (Public):${NC}  http://${PUBLIC_IP}:${WEB_PORT}"
echo -e "  ${BOLD}Web Dashboard (LAN):${NC}     http://${LOCAL_IP}:${WEB_PORT}"
echo -e "  ${BOLD}Web Dashboard (Local):${NC}   http://localhost:${WEB_PORT}"
echo ""
echo -e "  ${YELLOW}${BOLD}API Key:${NC}  ${API_KEY}"
echo ""
echo -e "${CYAN}════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}RIST Input Ports:${NC}   2030–2050/udp (per stream, auto-assigned)"
echo -e "  ${BOLD}RIST Output Ports:${NC}  5556–5576/udp (per stream, auto-assigned)"
echo ""
echo -e "  ${YELLOW}Tip:${NC} Make sure these ports are open in your firewall/VPS security group!"
echo ""
